### ISSUE TITLE
hi scraft i am 9luis from the discord (zsh config)

### ISSUE THREAD

**Issue by luis-07** [Scraft161/DWM-custom#2]
i am back on linux and need a minimal zsh config can i have yours ?

**Comment by Scraft161** [comment]
[Closed]
Reason: not related to project
Comment: Hi, I have put up a version over at [this gist](https://gist.github.com/Scraft161/dd5271b5315815247c5c60d06301f458), you may want to go through and uncomment some lines so things work as they should.

**Comment by luis-07** [comment]
thanks sorry for putting the issue here i coulndt find a better place to put the issue on
